// import { IGroup } from "./universal";

export const defaultProducts = [
  {
    id: "rzgk4e7",
    createdAt: Date.now(),
    groupName: "вода",
    elements: [
      {
        createdAt: Date.now(),
        id: "dhwa7ci",
        elementGroupId: "rzgk4e7",
        elementGroupName: "вода",
        elementName: "вода бутилированная",
        dimention: "mLt",
        quantity: "1500",
        ingredients: [],
      },
      {
        createdAt: Date.now(),
        dimention: "Lt",
        elementGroupId: "rzgk4e7",
        elementGroupName: "вода",
        elementName: "вода минеральная ",
        id: "bt0rgnj",
        quantity: "0.5",
        ingredients: [],
      },
    ],
  },
  {
    createdAt: Date.now(),
    groupName: "масло растительное",
    id: "cf78f2y",
    elements: [
      {
        createdAt: Date.now(),
        dimention: "mLt",
        elementGroupId: "cf78f2y",
        elementGroupName: "масло растительное",
        elementName: "масло подсолнечное",
        id: "h2qkwou",
        quantity: "300",
        ingredients: [],
      },
      {
        createdAt: Date.now(),
        dimention: "mLt",
        elementGroupId: "cf78f2y",
        elementGroupName: "масло растительное",
        elementName: "масло оливковое",
        id: "5kitw9a",
        quantity: "500",
        ingredients: [],
      },
    ],
  },
  {
    createdAt: Date.now(),
    groupName: "молочка",
    id: "tv7hcr0",
    elements: [
      {
        createdAt: Date.now(),
        dimention: "gr.",
        elementGroupId: "tv7hcr0",
        elementGroupName: "молочка",
        elementName: "масло сливочное",
        id: "h0z6ery",
        quantity: "100",
        ingredients: [],
      },

      {
        createdAt: Date.now(),
        dimention: "mLt",
        elementGroupId: "tv7hcr0",
        elementGroupName: "молочка",
        elementName: "молоко",
        id: "o2cvkj8",
        quantity: "800",
        ingredients: [],
      },
    ],
  },
  {
    createdAt: Date.now(),
    groupName: "мука",
    id: "lgwwcfr",
    elements: [
      {
        createdAt: Date.now(),
        dimention: "gr.",
        elementGroupId: "lgwwcfr",
        elementGroupName: "мука",
        elementName: "мука пшеничная",
        id: "xf77fgn",
        quantity: "500",
        ingredients: [],
      },
    ],
  },
  {
    createdAt: Date.now(),
    groupName: "мясо",
    id: "ah7g5zy",
    elements: [
      {
        createdAt: Date.now(),
        dimention: "kg",
        elementGroupId: "ah7g5zy",
        elementGroupName: "мясо",
        elementName: "свинина",
        id: "9hzyuvz",
        quantity: "1",
        ingredients: [],
      },

      {
        createdAt: Date.now(),
        dimention: "kg",
        elementGroupId: "ah7g5zy",
        elementGroupName: "мясо",
        elementName: "говядина",
        id: "ak0fu7x",
        quantity: "0.5",
        ingredients: [],
      },
    ],
  },
  {
    createdAt: Date.now(),
    groupName: "овощи",
    id: "2pezwmh",
    elements: [
      {
        createdAt: Date.now(),
        dimention: "kg",
        elementGroupId: "2pezwmh",
        elementGroupName: "овощи",
        elementName: "огурцы",
        id: "bniyznd",
        quantity: "0.5",
        ingredients: [],
      },

      {
        createdAt: Date.now(),
        dimention: "kg",
        elementGroupId: "2pezwmh",
        elementGroupName: "овощи",
        elementName: "помидоры",
        id: "lhx4wb8",
        quantity: "0.3",
        ingredients: [],
      },
      {
        createdAt: Date.now(),
        dimention: "kg",
        elementGroupId: "2pezwmh",
        elementGroupName: "овощи",
        elementName: "лук",
        id: "0y9oovq",
        quantity: "0",
        ingredients: [],
      },
      {
        createdAt: Date.now(),
        dimention: "kg",
        elementGroupId: "2pezwmh",
        elementGroupName: "овощи",
        elementName: "картофель",
        id: "z7gbgfc",
        quantity: "2",
        ingredients: [],
      },
    ],
  },
  {
    createdAt: Date.now(),
    groupName: "соль сахар",
    id: "rocqsw6",
    elements: [
      {
        createdAt: Date.now(),
        dimention: "gr.",
        elementGroupId: "rocqsw6",
        elementGroupName: "соль сахар",
        elementName: "сахар",
        id: "fj5o9gv",
        quantity: "1000",
        ingredients: [],
      },

      {
        createdAt: Date.now(),
        dimention: "gr.",
        elementGroupId: "rocqsw6",
        elementGroupName: "соль сахар",
        elementName: "соль",
        id: "xtj138o",
        quantity: "200",
        ingredients: [],
      },
    ],
  },
  {
    createdAt: Date.now(),
    groupName: "фрукты",
    id: "p3sw3c3",
    elements: [
      {
        createdAt: Date.now(),
        dimention: "kg",
        elementGroupId: "p3sw3c3",
        elementGroupName: "фрукты",
        elementName: "вишня",
        id: "tcqb092",
        quantity: "1",
        ingredients: [],
      },

      {
        createdAt: Date.now(),
        dimention: "kg",
        elementGroupId: "p3sw3c3",
        elementGroupName: "фрукты",
        elementName: "яблоки",
        id: "p3sw3c3",
        quantity: "0.5",
        ingredients: [],
      },
    ],
  },
  {
    createdAt: Date.now(),
    groupName: "яйца",
    id: "gb1ytxn",
    elements: [
      {
        createdAt: Date.now(),
        dimention: "pieces",
        elementGroupId: "gb1ytxn",
        elementGroupName: "яйца",
        elementName: "яйцо перепелиное",
        id: "yqdqo71",
        quantity: "5",
        ingredients: [],
      },

      {
        createdAt: Date.now(),
        dimention: "pieces",
        elementGroupId: "gb1ytxn",
        elementGroupName: "яйца",
        elementName: "яйцо куриное",
        id: "6ggq6ni",
        quantity: "8",
        ingredients: [],
      },
    ],
  },
];
