import { IGroup } from "./universal";


export const defaultRecipes:IGroup[] = [
  {
    createdAt: Date.now(),
    groupName: "блюда из яиц",
    id: "vkrtn6s",
    elements: [
      {
        createdAt: Date.now(),
        dimention: "---",
        elementGroupId: "vkrtn6s",
        elementGroupName: "блюда из яиц",
        elementName: "омлет",
        id: "fvlr38x",
        quantity: "2",
        ingredients: [
          {
            createdAt: Date.now(),
            dimention: "pieces",
            id: "vqp1scs",
            ingredientGroupId: "fvlr38x",
            ingredientName: "яйцо куриное",
            quantity: "3",
            serviceNumber: 20,
          },
          {
            createdAt: Date.now(),
            dimention: "mLt",
            id: "yd1wztp",
            ingredientGroupId: "fvlr38x",
            ingredientName: "масло подсолнечное",
            quantity: "25",
            serviceNumber: 8,
          },
          {
            createdAt: Date.now(),
            dimention: "mLt",
            id: "cbbyia1",
            ingredientGroupId: "fvlr38x",
            ingredientName: "молоко",
            quantity: "100",
            serviceNumber: 9,
          },
          {
            createdAt: Date.now(),
            dimention: "gr.",
            id: "eaoib1y",
            ingredientGroupId: "fvlr38x",
            ingredientName: "соль",
            quantity: "3",
            serviceNumber: 15,
          },
          {
            createdAt: Date.now(),
            dimention: "gr.",
            id: "54mbojr",
            ingredientGroupId: "fvlr38x",
            ingredientName: "мука пшеничная",
            quantity: "50",
            serviceNumber: 10,
          },
        ],
      },

      {
        createdAt: Date.now(),
        dimention: "---",
        elementGroupId: "vkrtn6s",
        elementGroupName: "блюда из яиц",
        elementName: "жареные",
        id: "e2h38dw",
        quantity: "1",
        ingredients: [
          {
            createdAt: Date.now(),
            dimention: "pieces",
            id: "d6kyann",
            ingredientGroupId: "e2h38dw",
            ingredientName: "яйцо куриное",
            quantity: "2",
            serviceNumber: 20,
          },
          {
            createdAt: Date.now(),
            dimention: "gr.",
            id: "wkilrfs",
            ingredientGroupId: "e2h38dw",
            ingredientName: "соль",
            quantity: "1",
            serviceNumber: 15,
          },
          {
            createdAt: Date.now(),
            dimention: "gr.",
            id: "zbde5t5",
            ingredientGroupId: "e2h38dw",
            ingredientName: "масло сливочное",
            quantity: "15",
            serviceNumber: 9,
          },
        ],
      },

      {
        createdAt: Date.now(),
        dimention: "---",
        elementGroupId: "vkrtn6s",
        elementGroupName: "блюда из яиц",
        elementName: "варёные",
        id: "8k4kjwh",
        quantity: "1",
        ingredients: [
          {
            createdAt: Date.now(),
            dimention: "pieces",
            id: "imohxf1",
            ingredientGroupId: "8k4kjwh",
            ingredientName: "яйцо куриное",
            quantity: "1",
            serviceNumber: 20,
          },
          {
            createdAt: Date.now(),
            dimention: "mLt",
            id: "jnh9xgn",
            ingredientGroupId: "8k4kjwh",
            ingredientName: "вода бутилированная",
            quantity: "400",
            serviceNumber: 2,
          },
          {
            createdAt: Date.now(),
            dimention: "gr.",
            id: "vjulaxk",
            ingredientGroupId: "8k4kjwh",
            ingredientName: "соль",
            quantity: "25",
            serviceNumber: 15,
          },
        ],
      },
    ],
  },

  {
    createdAt: Date.now(),
    groupName: "из картофеля",
    id: "u30w99p",
    elements: [
      {
        createdAt: Date.now(),
        dimention: "---",
        elementGroupId: "u30w99p",
        elementGroupName: "из картофеля",
        elementName: "жареная с луком",
        id: "yxlloeu",
        quantity: "4",
        ingredients: [
          {
            createdAt: Date.now(),
            dimention: "kg",
            id: "1xtrtaq",
            ingredientGroupId: "yxlloeu",
            ingredientName: "картофель",
            quantity: "0.8",
            serviceNumber: 5,
          },
          {
            createdAt: Date.now(),
            dimention: "kg",
            id: "41qc6li",
            ingredientGroupId: "yxlloeu",
            ingredientName: "лук",
            quantity: "0.2",
            serviceNumber: 6,
          },
          {
            createdAt: Date.now(),
            dimention: "mLt",
            id: "39pdggr",
            ingredientGroupId: "yxlloeu",
            ingredientName: "масло подсолнечное",
            quantity: "50",
            serviceNumber: 8,
          },
          {
            createdAt: Date.now(),
            dimention: "gr.",
            id: "kd1qfsh",
            ingredientGroupId: "yxlloeu",
            ingredientName: "масло сливочное",
            quantity: "30",
            serviceNumber: 9,
          },
          {
            createdAt: Date.now(),
            dimention: "gr.",
            id: "gwoxwy8",
            ingredientGroupId: "yxlloeu",
            ingredientName: "соль",
            quantity: "10",
            serviceNumber: 16,
          },
        ],
      },

      {
        createdAt: Date.now(),
        dimention: "---",
        elementGroupId: "u30w99p",
        elementGroupName: "из картофеля",
        elementName: "жареная",
        id: "hw4tjaq",
        quantity: "4",

        ingredients: [
          {
            createdAt: Date.now(),
            dimention: "kg",
            id: "ia413ia",
            ingredientGroupId: "hw4tjaq",
            ingredientName: "картофель",
            quantity: "1",
            serviceNumber: 5,
          },
          {
            createdAt: Date.now(),
            dimention: "mLt",
            id: "uuuo0dn",
            ingredientGroupId: "hw4tjaq",
            ingredientName: "масло подсолнечное",
            quantity: "50",
            serviceNumber: 8,
          },
          {
            createdAt: Date.now(),
            dimention: "gr.",
            id: "p4fufdp",
            ingredientGroupId: "hw4tjaq",
            ingredientName: "соль",
            quantity: "10",
            serviceNumber: 16,
          },
        ],
      },
    ],
  },

  {
    createdAt: Date.now(),
    groupName: "компот",
    id: "8vocxei",
    elements: [
      {
        createdAt: Date.now(),
        dimention: "---",
        elementGroupId: "8vocxei",
        elementGroupName: "компот",
        elementName: "вишнёвый",
        id: "qs347k5",
        quantity: "4",

        ingredients: [
          {
            createdAt: Date.now(),
            dimention: "kg",
            id: "6w237cu",
            ingredientGroupId: "qs347k5",
            ingredientName: "вишня",
            quantity: "0.5",
            serviceNumber: 1,
          },
          {
            createdAt: Date.now(),
            dimention: "mLt",
            id: "s8mcq0b",
            ingredientGroupId: "qs347k5",
            ingredientName: "вода бутилированная",
            quantity: "1000",
            serviceNumber: 1,
          },
          {
            createdAt: Date.now(),
            dimention: "gr.",
            id: "vmjziaq",
            ingredientGroupId: "qs347k5",
            ingredientName: "сахар",
            quantity: "200",
            serviceNumber: 13,
          },
        ],
      },
    ],
  },

  {
    createdAt: Date.now(),
    groupName: "мясные",
    id: "gz4q4q5",
    elements: [
      {
        createdAt: Date.now(),
        dimention: "---",
        elementGroupId: "gz4q4q5",
        elementGroupName: "мясные",
        elementName: "пельмени",
        id: "mk6ysjt",
        quantity: "10",

        ingredients: [
          {
            createdAt: Date.now(),
            dimention: "kg",
            id: "3ldyn5p",
            ingredientGroupId: "mk6ysjt",
            ingredientName: "говядина",
            quantity: "0.3",
            serviceNumber: 4,
          },
          {
            createdAt: Date.now(),
            dimention: "kg",
            id: "ie63bde",
            ingredientGroupId: "mk6ysjt",
            ingredientName: "свинина",
            quantity: "0.3",
            serviceNumber: 15,
          },
          {
            createdAt: Date.now(),
            dimention: "kg",
            id: "iwjukjs",
            ingredientGroupId: "mk6ysjt",
            ingredientName: "лук",
            quantity: "0.2",
            serviceNumber: 5,
          },
          {
            createdAt: Date.now(),
            dimention: "gr.",
            id: "8vovj4v",
            ingredientGroupId: "mk6ysjt",
            ingredientName: "соль",
            quantity: "10",
            serviceNumber: 14,
          },
          {
            createdAt: Date.now(),
            dimention: "mLt",
            id: "wdbm25a",
            ingredientGroupId: "mk6ysjt",
            ingredientName: "вода бутилированная",
            quantity: "250",
            serviceNumber: 2,
          },
          {
            createdAt: Date.now(),
            dimention: "pieces",
            id: "066yme1",
            ingredientGroupId: "mk6ysjt",
            ingredientName: "яйцо куриное",
            quantity: "1",
            serviceNumber: 16,
          },
          {
            createdAt: Date.now(),
            dimention: "gr.",
            id: "s6ljwkn",
            ingredientGroupId: "mk6ysjt",
            ingredientName: "мука пшеничная",
            quantity: "500",
            serviceNumber: 10,
          },
        ],
      },
    ],
  },

  {
    createdAt: Date.now(),
    groupName: "повидло",
    id: "0v3xtt4",
    elements: [
      {
        createdAt: Date.now(),
        dimention: "---",
        elementGroupId: "0v3xtt4",
        elementGroupName: "повидло",
        elementName: "яблочное",
        id: "qee9c9g",
        quantity: "6",

        ingredients: [
          {
            createdAt: Date.now(),
            dimention: "kg",
            id: "zkbgdcj",
            ingredientGroupId: "qee9c9g",
            ingredientName: "яблоки",
            quantity: "1",
            serviceNumber: 17,
          },
          {
            createdAt: Date.now(),
            dimention: "gr.",
            id: "c9i9lvs",
            ingredientGroupId: "qee9c9g",
            ingredientName: "сахар",
            quantity: "400",
            serviceNumber: 14,
          },
          {
            createdAt: Date.now(),
            dimention: "mLt",
            id: "bh3vnac",
            ingredientGroupId: "qee9c9g",
            ingredientName: "вода бутилированная",
            quantity: "500",
            serviceNumber: 2,
          },
        ],
      },
    ],
  },

  {
    createdAt: Date.now(),
    groupName: "салат",
    id: "ph3078k",

    elements: [
      {
        createdAt: Date.now(),
        dimention: "---",
        elementGroupId: "ph3078k",
        elementGroupName: "салат",
        elementName: "огурцы помидоры лук",
        id: "9r9bsig",
        quantity: "2",

        ingredients: [
          {
            createdAt: Date.now(),
            dimention: "kg",
            id: "sqc91mi",
            ingredientGroupId: "9r9bsig",
            ingredientName: "огурцы",
            quantity: "0.2",
            serviceNumber: 12,
          },
          {
            createdAt: Date.now(),
            dimention: "kg",
            id: "go71c2f",
            ingredientGroupId: "9r9bsig",
            ingredientName: "помидоры",
            quantity: "0.3",
            serviceNumber: 13,
          },
          {
            createdAt: Date.now(),
            dimention: "kg",
            id: "z9w739i",
            ingredientGroupId: "9r9bsig",
            ingredientName: "лук",
            quantity: "0.1",
            serviceNumber: 6,
          },
          {
            createdAt: Date.now(),
            dimention: "gr.",
            id: "y1tsixe",
            ingredientGroupId: "9r9bsig",
            ingredientName: "соль",
            quantity: "5",
            serviceNumber: 16,
          },
        ],
      },
    ],
  },
];
